project: odibi_local_project

connections:
  raw_data:
    type: local
    base_path: ./data/raw
  delta_lake:
    type: local
    base_path: ./data/lake

# Story (Documentation) Output
story:
  connection: delta_lake
  path: stories

pipelines:
  - pipeline: simple_etl
    nodes:
      - name: ingest_example
        # Example: Reading a CSV file (Ensure this file exists in data/raw/)
        read:
          connection: raw_data
          format: csv
          path: sample_data.csv
          # optional:
          # options:
          #   header: true

        # Transformer: Deduplicate
        transformer: deduplicate
        params:
          keys: ["id"]
          order_by: "updated_at DESC"

        # Transformation Steps
        transform:
          steps:
            - sql: |
                SELECT *,
                       'processed' as status
                FROM df

        # Write to Delta Lake (Local)
        write:
          connection: delta_lake
          format: delta
          path: silver/example_table
          mode: overwrite
