connections:
  local:
    base_path: .
    type: local
engine: pandas
pipelines:
- nodes:
  - name: load_customers
    read:
      connection: local
      format: csv
      path: c:\Users\hodibi\OneDrive - Ingredion\Desktop\Repos\Odibi\examples\diagnostics_demo\data\customers.csv
    write:
      connection: local
      format: delta
      mode: overwrite
      options:
        deep_diagnostics: true
        diff_keys:
        - id
        schema_mode: overwrite
      path: c:\Users\hodibi\OneDrive - Ingredion\Desktop\Repos\Odibi\examples\diagnostics_demo\output\raw_customers
  - name: load_transactions
    read:
      connection: local
      format: csv
      path: c:\Users\hodibi\OneDrive - Ingredion\Desktop\Repos\Odibi\examples\diagnostics_demo\data\transactions.csv
    write:
      connection: local
      format: delta
      mode: overwrite
      path: c:\Users\hodibi\OneDrive - Ingredion\Desktop\Repos\Odibi\examples\diagnostics_demo\output\raw_transactions
  - depends_on:
    - load_customers
    name: enrich_data
    params:
      segment_prefix: GLOBAL-
    transformer: enrich_customers
    write:
      connection: local
      format: delta
      mode: overwrite
      options:
        deep_diagnostics: true
        diff_keys:
        - id
        schema_mode: overwrite
      path: c:\Users\hodibi\OneDrive - Ingredion\Desktop\Repos\Odibi\examples\diagnostics_demo\output\enriched_customers
  - depends_on:
    - enrich_data
    - load_transactions
    name: join_data
    params: {}
    transformer: join_transactions
  - depends_on:
    - join_data
    name: summarize_stats
    params: {}
    transformer: summarize_customer
    write:
      connection: local
      format: delta
      mode: overwrite
      path: c:\Users\hodibi\OneDrive - Ingredion\Desktop\Repos\Odibi\examples\diagnostics_demo\output\customer_stats
  pipeline: customer_360
project: diagnostics_demo
story:
  connection: local
  path: c:\Users\hodibi\OneDrive - Ingredion\Desktop\Repos\Odibi\examples\diagnostics_demo\stories
version: 1.0.0
