# =============================================================================
# INGESTION PIPELINES (BRONZE)
# =============================================================================
# Focus: Reading raw data, basic type standardization, and loading.
# =============================================================================

pipelines:
  - pipeline: ingest_sales
    layer: bronze
    description: "Ingest daily sales CSVs"
    nodes:
      # ---------------------------------------------------------
      # 1. Read Raw CSV
      # ---------------------------------------------------------
      - name: load_csv
        read:
          connection: raw_data  # Defined in connections.yaml
          path: sales/daily_*.csv
          format: csv
          options: 
            header: true
        
        # Validation on read (Fail fast if bad data)
        validation:
          not_empty: true
          no_nulls: [transaction_id]

      # ---------------------------------------------------------
      # 2. Standardize Schema
      # ---------------------------------------------------------
      - name: standardize
        depends_on: [load_csv]
        transform:
          steps:
            # Cast types explicitly
            - |
              SELECT 
                CAST(transaction_id as STRING) as id,
                CAST(amount as DOUBLE) as amount,
                date_parse(transaction_date, '%Y-%m-%d') as txn_date
              FROM load_csv
        
        cache: true  # Cache this result as it might be used by multiple downstream pipelines

