# =============================================================================
# TRANSFORMATION PIPELINES (SILVER/GOLD)
# =============================================================================
# Focus: Business logic, aggregations, and metrics.
# =============================================================================

pipelines:
  - pipeline: transform_sales
    layer: silver
    description: "Calculate daily revenue"
    nodes:
      # ---------------------------------------------------------
      # 1. Aggregate Daily Revenue
      # ---------------------------------------------------------
      # Note: This node depends on 'standardize' from ingest_sales pipeline.
      # In a real scenario, you would pass that DataFrame via context or write/read it.
      # For this example, we assume 'standardize' is available in the execution context.
      - name: aggregate
        depends_on: [standardize]  
        transform:
            steps:
                - |
                  SELECT 
                    txn_date,
                    sum(amount) as total_revenue,
                    count(*) as txn_count
                  FROM standardize
                  GROUP BY txn_date
        
        # ---------------------------------------------------------
        # 2. Write to Processed
        # ---------------------------------------------------------
      - name: write_gold
        depends_on: [aggregate]
        write:
          connection: processed_data  # Defined in connections.yaml
          path: gold/daily_revenue.parquet
          format: parquet
          mode: overwrite

