project: Spark SQL Pipeline Example
engine: spark
description: "Demonstrates pure Spark SQL transformations"

connections:
  # In a real scenario, this would be ADLS/S3
  raw_data:
    type: local
    base_path: ./data/raw

  processed_data:
    type: local
    base_path: ./data/processed

story:
  connection: processed_data
  path: stories/
  auto_generate: true

pipelines:
  - pipeline: sales_analysis
    description: "Analyze sales data using Spark SQL"
    nodes:
      - name: load_transactions
        read:
          connection: raw_data
          path: transactions.csv
          format: csv
          options:
            header: true
            inferSchema: true
        cache: true

      - name: load_customers
        read:
          connection: raw_data
          path: customers.csv
          format: csv
          options:
            header: true
            inferSchema: true
        cache: true

      - name: clean_transactions
        depends_on: [load_transactions]
        transform:
          steps:
            - |
              SELECT 
                transaction_id,
                customer_id,
                to_date(transaction_date) as tx_date,
                amount,
                status
              FROM load_transactions
              WHERE amount > 0 AND status = 'COMPLETED'

      - name: customer_summary
        depends_on: [clean_transactions, load_customers]
        transform:
          steps:
            - |
              SELECT 
                c.customer_name,
                c.region,
                count(t.transaction_id) as tx_count,
                sum(t.amount) as total_spend,
                avg(t.amount) as avg_tx_value
              FROM clean_transactions t
              JOIN load_customers c ON t.customer_id = c.customer_id
              GROUP BY 1, 2
              ORDER BY total_spend DESC

      - name: save_summary
        depends_on: [customer_summary]
        write:
          connection: processed_data
          path: customer_summary
          format: delta
          mode: overwrite
