# ============================================
# Delta Lake ACID Template
# ============================================
# Best for: Transactional data lakes
# --------------------------------------------
project: Delta Lake Demo
engine: pandas

connections:
  lake:
    type: local
    base_path: ./lakehouse

pipelines:
  - pipeline: upsert_pattern
    nodes:
      - name: new_data
        read:
          connection: lake
          path: landing/daily.csv
          format: csv
          
      - name: merge_to_silver
        depends_on: [new_data]
        write:
          connection: lake
          path: silver/customers
          format: delta
          mode: append
          options:
            mergeSchema: true
