version: 1
project: Customer PII Pipeline
engine: pandas

connections:
  secure_source:
    type: local
    base_path: ./data/secure
  analytics_sink:
    type: local
    base_path: ./data/analytics

story:
  connection: analytics_sink
  path: stories/audit_logs/

pipelines:
  - pipeline: process_customer_data
    description: "Ingest customer data with automatic PII redaction"
    nodes:
      # 1. Redact specific columns
      # Useful when you want to debug non-sensitive fields but hide keys
      - name: ingest_crm_data
        read:
          connection: secure_source
          path: customers.csv
          format: csv
        sensitive: ["ssn", "credit_card", "email"]  # <--- Specific Redaction

      # 2. Full Redaction
      # Useful for highly sensitive transformations where no data should leak
      - name: join_medical_records
        depends_on: [ingest_crm_data]
        transform:
          steps:
            - "SELECT * FROM ${source} WHERE risk_score > 0.8"
        sensitive: true  # <--- Full Redaction (Redacts ALL columns in report)

      # 3. Safe Output
      # Writing is not redacted (data moves), but the *report* is.
      - name: save_risk_report
        depends_on: [join_medical_records]
        write:
          connection: analytics_sink
          path: risk_report.parquet
          format: parquet
