"""Core components for the Odibi AI Agent Suite."""

from odibi.agents.core.agent_base import (
    AgentContext,
    AgentPermissions,
    AgentRegistry,
    AgentResponse,
    AgentRole,
    OdibiAgent,
)
from odibi.agents.core.azure_client import (
    AzureConfig,
    AzureOpenAIClient,
    AzureSearchClient,
    get_odibi_index_schema,
)
from odibi.agents.core.chroma_store import ChromaVectorStore
from odibi.agents.core.code_parser import CodeChunk, OdibiCodeParser, parse_odibi_codebase
from odibi.agents.core.cycle import (
    GoldenProjectConfig,
    GoldenProjectResult,
    RegressionCheckResult,
    parse_golden_projects_input,
)
from odibi.agents.core.embeddings import (
    AzureEmbedder,
    BaseEmbedder,
    LocalEmbedder,
    get_default_embedder,
)
from odibi.agents.core.enforcement import (
    CycleExitStatus,
    CycleTerminationEnforcer,
    EnforcementError,
    PermissionDeniedError,
    PermissionEnforcer,
    ReviewDecision,
    ReviewGateEnforcer,
    ReviewGatingError,
    WallClockEnforcer,
    WallClockTimeoutError,
)
from odibi.agents.core.index_manager import ensure_index, get_index, needs_reindex
from odibi.agents.core.memory import Memory, MemoryManager, MemoryStore, MemoryType
from odibi.agents.core.memory_guardrails import (
    MemoryQuery,
    MemoryQueryIntent,
    MemoryQueryResult,
    MemoryQueryValidator,
)
from odibi.agents.core.proposal_scorecard import (
    GoldenProjectCoverage,
    ProposalScorecard,
    ScoreLevel,
    ScorecardDimension,
    ScorecardGenerator,
)
from odibi.agents.core.review_context import (
    ADVISORY_DISCLAIMER,
    AdvisoryContext,
    FileChangeSummary,
    ReviewContextEnricher,
)
from odibi.agents.core.memory_access import (
    MemoryAccessLevel,
    can_query_memory,
    generate_contract_documentation,
    get_allowed_intents,
    get_memory_access,
    validate_query_for_role,
)
from odibi.agents.core.schemas import (
    ImprovementProposal,
    IssueSeverity,
    IssueType,
    ObservedIssue,
    ObserverOutput,
    ProposalChange,
    ProposalImpact,
    ProposalRisk,
    ReviewerValidation,
)
from odibi.agents.core.vector_store import BaseVectorStore
from odibi.agents.core.autonomous_learning import (
    AutonomousLearningScheduler,
    AutonomousLearningSession,
    AutonomousLearningStatus,
    GuardedCycleRunner,
    LearningCycleConfig,
    LearningCycleResult,
    LearningModeGuard,
    LearningModeViolation,
    validate_learning_profile,
)
from odibi.agents.core.cycle_profile import (
    CycleProfile,
    CycleProfileError,
    CycleProfileLoader,
    CycleSourceConfigSchema,
    FrozenCycleProfile,
    GuardrailsSchema,
    ProfileMetadataSchema,
    compute_profile_hash,
    freeze_profile,
    load_profile_yaml,
    validate_profile,
)
from odibi.agents.core.disk_guard import (
    DEFAULT_ARTIFACTS_BUDGET_BYTES,
    DEFAULT_INDEX_BUDGET_BYTES,
    DEFAULT_REPORTS_BUDGET_BYTES,
    DiskGuardError,
    DiskGuardReport,
    DiskUsageGuard,
    DiskUsageSummary,
    HeartbeatData,
    HeartbeatWriter,
    ReportErrorWriter,
    RotationResult,
)
from odibi.agents.core.observation_integrity import (
    ObservationIntegrityCheck,
    ObservationIntegrityError,
    check_observer_convergence_consistency,
    count_pipeline_failures_from_evidence,
    validate_observation_summary,
    validate_observer_output_integrity,
)
from odibi.agents.core.pipeline_status import (
    PipelineExecutionResult,
    PipelineExecutionStatus,
    PipelineValidationError,
    create_pipeline_result_from_execution,
    detect_pipeline_status,
    parse_validation_errors,
)
from odibi.agents.core.issue_discovery import (
    ConfidenceLevel,
    DiscoveredIssue,
    DiscoveredIssueType,
    IssueDiscoveryManager,
    IssueDiscoveryResult,
    IssueEvidence,
    IssueLocation,
    PassiveIssueDetector,
    UserIssueSelection,
)
from odibi.agents.core.issue_to_improvement import (
    IssueImprovementIntegrationError,
    IssueImprovementIntegrator,
    IssueImprovementRequest,
    create_improvement_from_discovery,
)

__all__ = [
    "AgentContext",
    "AgentPermissions",
    "AgentRegistry",
    "AgentResponse",
    "AgentRole",
    "AzureConfig",
    "AzureEmbedder",
    "AzureOpenAIClient",
    "AzureSearchClient",
    "BaseEmbedder",
    "BaseVectorStore",
    "ChromaVectorStore",
    "CodeChunk",
    "CycleExitStatus",
    "CycleTerminationEnforcer",
    "EnforcementError",
    "GoldenProjectConfig",
    "GoldenProjectResult",
    "ImprovementProposal",
    "IssueSeverity",
    "IssueType",
    "LocalEmbedder",
    "Memory",
    "MemoryManager",
    "MemoryQuery",
    "MemoryQueryIntent",
    "MemoryQueryResult",
    "MemoryQueryValidator",
    "MemoryStore",
    "MemoryType",
    "GoldenProjectCoverage",
    "ProposalScorecard",
    "ScoreLevel",
    "ScorecardDimension",
    "ScorecardGenerator",
    "ADVISORY_DISCLAIMER",
    "AdvisoryContext",
    "FileChangeSummary",
    "ReviewContextEnricher",
    "MemoryAccessLevel",
    "can_query_memory",
    "generate_contract_documentation",
    "get_allowed_intents",
    "get_memory_access",
    "validate_query_for_role",
    "ObservedIssue",
    "ObserverOutput",
    "OdibiAgent",
    "OdibiCodeParser",
    "PermissionDeniedError",
    "PermissionEnforcer",
    "ProposalChange",
    "ProposalImpact",
    "ProposalRisk",
    "RegressionCheckResult",
    "ReviewDecision",
    "ReviewGateEnforcer",
    "ReviewGatingError",
    "ReviewerValidation",
    "WallClockEnforcer",
    "WallClockTimeoutError",
    "ensure_index",
    "get_default_embedder",
    "get_index",
    "get_odibi_index_schema",
    "needs_reindex",
    "parse_golden_projects_input",
    "parse_odibi_codebase",
    # Phase 9.A: Autonomous Learning
    "AutonomousLearningScheduler",
    "AutonomousLearningSession",
    "AutonomousLearningStatus",
    "GuardedCycleRunner",
    "LearningCycleConfig",
    "LearningCycleResult",
    "LearningModeGuard",
    "LearningModeViolation",
    "validate_learning_profile",
    # Phase 9.A: Disk Guard & Observability
    "DEFAULT_ARTIFACTS_BUDGET_BYTES",
    "DEFAULT_INDEX_BUDGET_BYTES",
    "DEFAULT_REPORTS_BUDGET_BYTES",
    "DiskGuardError",
    "DiskGuardReport",
    "DiskUsageGuard",
    "DiskUsageSummary",
    "HeartbeatData",
    "HeartbeatWriter",
    "ReportErrorWriter",
    "RotationResult",
    # Phase 9.C: Cycle Profiles
    "CycleProfile",
    "CycleProfileError",
    "CycleProfileLoader",
    "CycleSourceConfigSchema",
    "FrozenCycleProfile",
    "GuardrailsSchema",
    "ProfileMetadataSchema",
    "compute_profile_hash",
    "freeze_profile",
    "load_profile_yaml",
    "validate_profile",
    # Phase 9.F: Observation Integrity
    "ObservationIntegrityCheck",
    "ObservationIntegrityError",
    "check_observer_convergence_consistency",
    "count_pipeline_failures_from_evidence",
    "validate_observation_summary",
    "validate_observer_output_integrity",
    "PipelineExecutionResult",
    "PipelineExecutionStatus",
    "PipelineValidationError",
    "create_pipeline_result_from_execution",
    "detect_pipeline_status",
    "parse_validation_errors",
    # Phase 10: Issue Discovery
    "ConfidenceLevel",
    "DiscoveredIssue",
    "DiscoveredIssueType",
    "IssueDiscoveryManager",
    "IssueDiscoveryResult",
    "IssueEvidence",
    "IssueLocation",
    "PassiveIssueDetector",
    "UserIssueSelection",
    # Phase 10.D: Issue-to-Improvement Integration
    "IssueImprovementIntegrationError",
    "IssueImprovementIntegrator",
    "IssueImprovementRequest",
    "create_improvement_from_discovery",
]
