"""Build the packaged agent corpus shipped inside the wheel.

Copies the user-facing docs, all worked examples, and the .assistant skills into
``odibi_mcp/_corpus/`` and generates a lightweight ``index.json`` so the MCP can
serve and search them when there's no repo (pip-install mode).

The generated tree is committed so it ships reliably via ``include-package-data``
(a setuptools build hook would not be verifiable before a release). A CI test
re-runs this and asserts the committed copy is in sync.

Run:  python scripts/build_corpus.py
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CORPUS = REPO / "odibi_mcp" / "_corpus"

# User-facing doc subtrees (project-meta like internal/implementation/plans/
# video-scripts is intentionally excluded — not useful to a pipeline-building agent).
DOC_DIRS = [
    "features",
    "guides",
    "patterns",
    "tutorials",
    "reference",
    "validation",
    "simulation",
    "skills",
    "examples",
]
# High-value top-level docs to include if present.
DOC_TOP_FILES = [
    "ODIBI_DEEP_CONTEXT.md",
    "golden_path.md",
    "troubleshooting.md",
    "index.md",
]


def _title_and_summary(md_path: Path) -> tuple[str, str]:
    """First H1 (or filename) as title; first non-heading, non-blank line as summary."""
    title = md_path.stem
    summary = ""
    try:
        lines = md_path.read_text(encoding="utf-8").splitlines()
    except Exception:
        return title, summary
    for line in lines:
        s = line.strip()
        if s.startswith("# ") and title == md_path.stem:
            title = s[2:].strip()
        elif s and not s.startswith("#") and not s.startswith("---") and not summary:
            summary = s[:200]
        if title != md_path.stem and summary:
            break
    return title, summary


def _copy_docs() -> list[Path]:
    src_docs = REPO / "docs"
    dst_docs = CORPUS / "docs"
    copied: list[Path] = []
    for sub in DOC_DIRS:
        s = src_docs / sub
        if s.is_dir():
            d = dst_docs / sub
            shutil.copytree(s, d, ignore=shutil.ignore_patterns("*.png", "*.jpg", "*.gif", "*.svg"))
            copied.extend(d.rglob("*.md"))
    for fname in DOC_TOP_FILES:
        s = src_docs / fname
        if s.is_file():
            shutil.copy2(s, dst_docs / fname)
            copied.append(dst_docs / fname)
    return copied


def _copy_examples() -> None:
    src = REPO / "examples"
    dst = CORPUS / "examples"
    if not src.is_dir():
        return
    for ext in ("*.yaml", "*.yml"):
        for f in src.rglob(ext):
            rel = f.relative_to(src)
            target = dst / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, target)


def _copy_assistant() -> None:
    src = REPO / ".assistant"
    if not src.is_dir():
        return
    shutil.copytree(src, CORPUS / ".assistant")
    # setuptools won't package a leading-dot *filename*, so also emit the
    # instructions under a non-dot name that the package-data globs match.
    dot_instr = src / ".assistant_instructions.md"
    if dot_instr.is_file():
        shutil.copy2(dot_instr, CORPUS / ".assistant" / "instructions.md")


def _build_index(doc_files: list[Path]) -> None:
    entries = []
    for md in sorted(doc_files):
        rel = md.relative_to(CORPUS)
        title, summary = _title_and_summary(md)
        entries.append(
            {
                "path": str(rel).replace("\\", "/"),
                "title": title,
                "section": rel.parts[1] if len(rel.parts) > 2 else "docs",
                "summary": summary,
            }
        )
    (CORPUS / "index.json").write_text(
        json.dumps({"docs": entries}, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def main() -> None:
    if CORPUS.exists():
        shutil.rmtree(CORPUS)
    CORPUS.mkdir(parents=True)
    (CORPUS / "README.md").write_text(
        "# Packaged Odibi agent corpus\n\n"
        "Generated by `scripts/build_corpus.py` — DO NOT EDIT BY HAND.\n"
        "Source of truth is the repo's `docs/`, `examples/`, and `.assistant/`.\n",
        encoding="utf-8",
    )
    doc_files = _copy_docs()
    _copy_examples()
    _copy_assistant()
    _build_index(doc_files)
    n_examples = (
        len(list((CORPUS / "examples").rglob("*.y*ml"))) if (CORPUS / "examples").is_dir() else 0
    )
    print(f"Corpus built: {len(doc_files)} docs, {n_examples} examples -> {CORPUS}")


if __name__ == "__main__":
    main()
