project: HR Analytics Pipeline
engine: pandas

connections:
  source_data:
    type: local
    base_path: ./data
  
  analytics_store:
    type: local
    base_path: ./output

story:
  connection: analytics_store
  path: stories/
  max_sample_rows: 10

pipelines:
  - pipeline: payroll_processing
    description: "Calculate bonuses and aggregate department stats"
    nodes:
      # 1. Load Data
      - name: load_employees
        read:
          connection: source_data
          path: employees.csv
          format: csv
      
      - name: load_departments
        read:
          connection: source_data
          path: departments.csv
          format: csv

      # 2. Custom Python Transforms (from transforms.py)
      - name: calculate_employee_bonus
        depends_on: [load_employees]
        transform:
          steps:
            - function: calculate_bonus
              params:
                employee_data: load_employees
                bonus_multiplier: 2000.0

      - name: generate_emails
        depends_on: [calculate_employee_bonus]
        transform:
          steps:
            - function: email_generator
              params:
                source_data: calculate_employee_bonus
                domain: "odibi.data"

      # 3. SQL Transform (Join & Filter)
      - name: joined_data
        depends_on: [generate_emails, load_departments]
        transform:
          steps:
            - |
              SELECT 
                e.id, e.name, e.email, e.salary, e.bonus, e.status,
                d.dept_name, d.location
              FROM generate_emails e
              JOIN load_departments d ON e.dept_id = d.dept_id
              WHERE d.location = 'New York'

      # 4. SQL Transform (Aggregation)
      - name: dept_summary
        depends_on: [joined_data]
        transform:
          steps:
            - |
              SELECT 
                dept_name,
                COUNT(*) as employee_count,
                SUM(salary) as total_salary,
                AVG(bonus) as avg_bonus
              FROM joined_data
              GROUP BY dept_name

      # 5. Write Outputs
      - name: save_enriched_employees
        depends_on: [joined_data]
        write:
          connection: analytics_store
          path: ny_employees.parquet
          format: parquet
          mode: overwrite

      - name: save_summary
        depends_on: [dept_summary]
        write:
          connection: analytics_store
          path: department_stats.csv
          format: csv
          mode: overwrite
