project: fail_test
engine: pandas
connections:
  raw_data:
    type: local
    base_path: ./data/raw
  delta_lake:
    type: local
    base_path: ./data/lake
story:
  connection: delta_lake
  path: stories

pipelines:
  - pipeline: fail_fast_pipeline
    nodes:
      - name: fail_node
        read:
          connection: raw_data
          format: csv
          path: sample_data.csv
        contracts:
          - type: "row_count"
            min: 1000 # Will Fail
        write:
          connection: delta_lake
          format: delta
          path: silver/fail

      - name: success_node
        read:
          connection: raw_data
          format: csv
          path: sample_data.csv
        contracts:
          - type: "row_count"
            min: 1
        write:
          connection: delta_lake
          format: delta
          path: silver/success
